#- debug: msg="{{container_infos}}"
#- fail:

- name: Run containers
  include_tasks: run_container.yaml
  with_dict: "{{container_infos}}"
  loop_control: { loop_var: info }
  vars:
    container_info: |
      {{"
      info=Box(info,default_box=True)
      info.name=info.name or target_name
      if name_prefix:
          info.name='_'.join([name_prefix,info.name])
      info.hostname=info.hostname or info.name
      out=Box(
        env=dict(TZ='Asia/Almaty'),
        comparisons={'*': 'strict'},
        networks_cli_compatible=False) + info
      out=out.to_dict()
      "|eval(info=info.value,target_name=target_name,
      name_prefix=container_vars.name_prefix|default(''))
      }}
