- set_fact:
    "{{file_var.key}}": "{{file_var.value}}"
  with_dict: "{{file_vars|default({})}}"
  loop_control: { loop_var: file_var }

- name: "Reading {{set_to}}"
  include_vars:
    file: "{{input_file}}"
    name: "temp_data"

#- debug: msg="{{temp_data}}"

- name: "Setting {{set_to}}"
  envise:
    env_name: "{{env_name}}"
    env_names: "{{env_names|default([])}}"
    input: "{{temp_data}}"
    set_to: "{{set_to}}"

#- debug: msg="{{lookup('vars',set_to)}}"
