default:
  backend:
    image: "kartoza/postgis:13-3.1"
    volumes:
      - "{{infra_volumes_dir}}/{{project_name}}_backend_{{backend_target}}:/var/lib/postgresql"
    env:
      ALLOW_IP_RANGE: "0.0.0.0/0"
      DEFAULT_ENCODING: "UTF8"
      POSTGRES_USER: "{{infra.DB.username}}"
      POSTGRES_PASS: "{{infra.DB.password}}"
      POSTGRES_DBNAME: [ Not set ]
      POSTGRES_MULTIPLE_EXTENSIONS: "postgis,hstore,postgis_topology"
      DEFAULT_COLLATION: "en_US.UTF-8"
      DEFAULT_CTYPE: "en_US.UTF-8"
      EXTRA_CONF: "max_connections = 500"

