default:
  portainer:
    image: 'portainer/portainer-ce:2.5.1'
    name: portainer
    ports:
      - "9000:9000"
    volumes:
      - "{{infra_volumes_dir}}/portainer_data:/data"
      - /var/run/docker.sock:/var/run/docker.sock
    restart_policy: always



