- hosts: all
  vars:
    roles_location: ../roles/lgblkb
    pull_project: yes
  tasks:
    - include_role: { name: "{{roles_location}}", tasks_from: base }
    - name: 'Create project networks'
      docker_network: "{{item}}"
      loop: "{{docker_infra.networks|default([])}}"
    - debug: msg="Project basement established!"