- hosts: all
  vars:
    roles_location: ../roles/lgblkb
  tasks:
    - include_role: { name: "{{roles_location}}", tasks_from: generate_ansible_secret }
      when: ansible_connection=='local'

    - include_role: { name: "{{roles_location}}", tasks_from: pull_project }
      when: ansible_connection!='local'

    - name: Install provision dependencies
      pip:
        requirements: "{{project_folder}}/provision/roles/lgblkb/files/.requirements.txt"
      when: ansible_connection!='local'

    - name: Create .env
      copy:
        content: ""
        dest: "{{project_folder}}/.env"
        force: no

    - debug: msg="Project initialized!"