- hosts: all
  vars:
    build_docker_image: yes
    show_container_details: no
    launch_container: yes
    pull_project: yes
    roles_location: ../roles/lgblkb
  tasks:
    - include_role: { name: "{{roles_location}}", tasks_from: base }

    - name: Build docker image
      shell: "{{project_tasks.docker_build}}"
      when: build_docker_image

    - include_role: { name: "{{roles_location}}", tasks_from: deploy }
      loop_control: { loop_var: switch_info }
      with_dict:
        service_switch: ../deploy_switches/service.yaml

    - debug: msg="Deployment successfull!"
