all:
  hosts:
    #    aws_server:
    #      ansible_host: 35.154.215.124
    #      ansible_user: ubuntu
    #      #      ansible_python_interpreter: "/usr/bin/python3"
    #      ansible_python_interpreter: "/home/ubuntu/.cache/pypoetry/virtualenvs/imagiflow-mfGYrIIF-py3.8/bin/python"
    #      project_folder: "/home/ubuntu/egistic/imagiflow"
    #      key_file: "~/.ssh/aws_server_rsa"
    #      infra_volumes_dir: "/mnt/efs/fs1/{{project_name}}_infra_volumes"
    frankfurt:
      ansible_host: 54.93.234.138
      ansible_user: ubuntu
      #      ansible_python_interpreter: "/usr/bin/python3"
      ansible_python_interpreter: "/home/ubuntu/.cache/pypoetry/virtualenvs/suoperres-n3Ouuj1Q-py3.8/bin/python"
      project_folder: "/home/ubuntu/egistic/superres"
      ansible_ssh_private_key_file: "~/Documents/egistic.pem"
      key_file: "~/.ssh/zhamilya_rsa"
      #      key_file: "~/Documents/egistic.pem"
      #      infra_volumes_dir: "/nfs/storage/{{project_name}}_infra_volumes"
      infra_volumes_dir: "/mnt/efs/fs1/{{project_name}}_infra_volumes"
  vars:
    env_name: "production"
    build_target: 'builder'



