all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "/home/zhamilya/.cache/pypoetry/virtualenvs/suoperres-e4LdXrr0-py3.8/bin/python"
      project_folder: "{{playbook_dir|dirname|dirname}}"
  vars:
    env_name: "development"
    build_target: 'builder'
    infra_volumes_dir: "/storage/infra_volumes"




